### ISSUE TITLE
Arduino and LIN

### ISSUE THREAD

**Issue by RaakeshRaja** [zapta/linbus#26]
I have been working on a project to make 2 Arduino mega boards communicate with each other over a LIN bus.
I use the LIN breakout boards from the following vendor.
[http://copperhilltech.com/lin-bus-breakout-board/]
I wanted to send commands from the master Arduino to the slave Arduino, where an LED is turned on or off.

**Comment by coryjfowler** [comment]
@RaakeshRaja This is an issue reporting system, and you are currently abusing it...
