### ISSUE TITLE
Replacement of ATA6631/ATA6625

### ISSUE THREAD

**Issue by Yannik** [zapta/linbus#27]
Both ATA6631 and ATA6625 have been deprecated by Microchip Technologies and can no longer be bought through the usual distributors. 

Is there any IC that can be used as a drop-in replacement?

**Comment by Yannik** [comment]
Possibly the MCP2025? http://ww1.microchip.com/downloads/en/DeviceDoc/20002306B.pdf

**Comment by AstronBnX** [comment]
You may use TJA1020 https://www.nxp.com/docs/en/data-sheet/TJA1020.pdf

**Comment by Yannik** [comment]
@AstronBnX TJA1020 has a different pinout than ATA6631/ATA6625

**Comment by AstronBnX** [comment]
@Yannik yes, you are right different pinouts but it is cheap. I'm also trying to get data from LINbus.

**Comment by wchpikus** [comment]
And tja1020 working the same? Is it tested?
Second question, icm on volvo is master yes?

**Comment by Yannik** [comment]
@wchpikus No, TJA1020 can not be used.

However, MCP2025 is a suitable replacement. I'm using MCP2025 and it works perfectly.

**Comment by wchpikus** [comment]
i ordered ATA6631 for 1$ per pcs.
tnx
here is link to shop:
https://www.alibaba.com/product-detail/-Electronic-Component-ATA6631_60829982565.html?spm=a2700.7724838.2017115.2.78d53e16h5sr9M
